///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PST_GlobParams
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PST_GlobParamsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6dd04083-9152-43b1-8dc1-7307e2ee24f4")]
    public partial class PST_GlobParamsRepository : RepoGenBaseFolder
    {
        static PST_GlobParamsRepository instance = new PST_GlobParamsRepository();
        PST_GlobParamsRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder _edgewordsshopecommercedemositefor;

        /// <summary>
        /// Gets the singleton class instance representing the PST_GlobParamsRepository element repository.
        /// </summary>
        [RepositoryFolder("6dd04083-9152-43b1-8dc1-7307e2ee24f4")]
        public static PST_GlobParamsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PST_GlobParamsRepository() 
            : base("PST_GlobParamsRepository", "/", null, 0, false, "6dd04083-9152-43b1-8dc1-7307e2ee24f4", ".\\RepositoryImages\\PST_GlobParamsRepository6dd04083.rximgres")
        {
            _edgewordsshopecommercedemositefor = new PST_GlobParamsRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6dd04083-9152-43b1-8dc1-7307e2ee24f4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EdgewordsShopECommerceDemoSiteFor folder.
        /// </summary>
        [RepositoryFolder("a4568db7-725e-42af-bd63-3b27039ea405")]
        public virtual PST_GlobParamsRepositoryFolders.EdgewordsShopECommerceDemoSiteForAppFolder EdgewordsShopECommerceDemoSiteFor
        {
            get { return _edgewordsshopecommercedemositefor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PST_GlobParamsRepositoryFolders
    {
        /// <summary>
        /// The EdgewordsShopECommerceDemoSiteForAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4568db7-725e-42af-bd63-3b27039ea405")]
        public partial class EdgewordsShopECommerceDemoSiteForAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputtagsInfo;

            /// <summary>
            /// Creates a new EdgewordsShopECommerceDemoSiteFor  folder.
            /// </summary>
            public EdgewordsShopECommerceDemoSiteForAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgewordsShopECommerceDemoSiteFor", "/dom[@domain='www.edgewordstraining.co.uk']", parentFolder, 30000, null, false, "a4568db7-725e-42af-bd63-3b27039ea405", "")
            {
                _inputtagsInfo = new RepoItemInfo(this, "InputTagS", ".//header[#'masthead']//form[@action='https://www.edgewordstraining.co.uk/demo-site/']/input[@name='s']", 30000, null, "2bb3868a-a2fe-422d-aff8-314cbe39999d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4568db7-725e-42af-bd63-3b27039ea405")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4568db7-725e-42af-bd63-3b27039ea405")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputTagS item.
            /// </summary>
            [RepositoryItem("2bb3868a-a2fe-422d-aff8-314cbe39999d")]
            public virtual Ranorex.InputTag InputTagS
            {
                get
                {
                    return _inputtagsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagS item info.
            /// </summary>
            [RepositoryItemInfo("2bb3868a-a2fe-422d-aff8-314cbe39999d")]
            public virtual RepoItemInfo InputTagSInfo
            {
                get
                {
                    return _inputtagsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
